apiVersion: v1
kind: Service
metadata:
  name: exampleapp
  namespace: example
spec:
  type: NodePort
  selector:
    app: exampleapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
